name: Catharsis
favicon: null
layout_spectrum: 1
typography_spectrum: 0.0896
title: Catharsis
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebdfd0'
    - '#d3bca3'
    - '#2e4d3e'
    - '#4d715f'
    - '#aca596'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
