name: Catharsis
favicon: null
layout_spectrum: 1
typography_spectrum: 0.0896
title: Catharsis
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#20221d'
    - '#5d5759'
    - '#a197ae'
    - '#867d8f'
    - '#72293f'
  brandStrength: 0.875
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 1
purpose: []
