name: Catharsis
favicon: null
layout_spectrum: 0.9159436714835465
typography_spectrum: 0.6502599245868623
title: Catharsis
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3189109698869288
  lightness: 0.1026084735058248
  saturation: 0.9675002410076559
  rhythmicContrast: 0.0312155622523278
purpose: []
