name: Catharsis
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Catharsis
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4c7d7e'
    - '#70a09f'
    - '#97bebd'
    - '#0c0f16'
    - '#c2dcd7'
  brandStrength: 0.875
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 1
purpose: []
